packages:
  - packages/kit

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@tsconfig/node20': ^20.1.4
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.7.4
  '@vue/tsconfig': ^0.5.1
  eslint: ^9.15.1
  eslint-plugin-format: ^1.0.1
  jsdom: ^24.1.3
  typescript: ~5.7.3
  vite: ^6.0.0
  # vite-plugin-dts 4.5.1 breaks, don't upgrade without testing
  vite-plugin-dts: 4.5.0
  vitest: ^2.1.5
